name: "assign reviewers"

on: pull_request

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          # config: ".github/assign-reviewers.txt"
          token: ${{ secrets.PERSONAL_TOKEN }}
          # token: ${{ secrets.GITHUB_TOKEN }}
